---
- name: stop servers
  hosts: localhost
  connection: local
  gather_facts: no

  tasks: 
    - name: Install Apache on EC2
      amazon.aws.ec2_instance:
        aws_access_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
        aws_secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        instance_ids:
          - i-xxxxxxxxxxxxxxxxx
          - i-xxxxxxxxxxxxxxxxx 
        instance_type: t2.micro
        key_name: Keypair1
        region: us-east-2
        state: stopped
        wait: yes
      register: stop
