---
- name: Terminate multiple EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Terminate multiple EC2 Instance
      amazon.aws.ec2_instance:
        aws_access_key: xxxxxxxxxxxxxxxxxxxxxxx
        aws_secret_key: xxxxxxxxxxxxxxxxxxxxxxx
        instance_type: t2.micro
        instance_ids: 
          - i-xxxxxxxxxxxxxxxxx
          - i-xxxxxxxxxxxxxxxxx
        key_name: xxxxxxxx
        image_ids: ami-xxxxxxxxxxxxxxxxx 
        region: us-east-2
        state: absent
        vpc_subnet_id: subnet-xxxxxxxxxxxxxxxxxx
        security_groups: 
          - sg-xxxxxxxxxxxxxxxxx
          - sg-xxxxxxxxxxxxxxxxx
        wait: yes
      register: termination
